name: Prepare Tests for BrowserStack

on:
  workflow_dispatch:
    inputs:
      test_folders:
        description: 'Folders containing tests to prepare (comma-separated, e.g., searchTests,cartTests)'
        required: true
        type: string
        default: 'searchTests'
      app_id:
        description: 'App ID to use in tests'
        required: true
        type: string
        default: 'com.example.app'

jobs:
  prepare-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup test directory structure
        run: |
          # Create temp directory structure
          mkdir -p temp_tests
          
          # Copy required directories and files
          cp -r generics temp_tests/
          cp -r screens temp_tests/
          cp generics/configuration/config.js temp_tests/
          
          # Create directory for tests
          mkdir -p temp_tests/copied_tests
          
          # Convert comma-separated list to array and copy each folder
          IFS=',' read -ra FOLDERS <<< "${{ inputs.test_folders }}"
          for folder in "${FOLDERS[@]}"; do
            # Remove any whitespace
            folder=$(echo $folder | xargs)
            echo "Processing folder: $folder"
            cp -r tests/$folder temp_tests/
          done
          
          # Update paths in test files (../../ to ./)
          find temp_tests -name "*.yaml" -type f -exec sed -i 's|../../generics|./generics|g' {} +
          find temp_tests -name "*.yaml" -type f -exec sed -i 's|../../screens|./screens|g' {} +
          
          # Update APP_ID in all yaml files
          find temp_tests -name "*.yaml" -type f -exec sed -i "s|\${env.APP_ID}|${{ inputs.app_id }}|g" {} +
          find temp_tests -name "*.yaml" -type f -exec sed -i "s|\${APP_ID}|${{ inputs.app_id }}|g" {} +
          
          # Create list of visible files only and copy them
          cd temp_tests
          find . \( ! -regex '.*/\..*' \) -type f > ../visible_files.txt
          mkdir -p ../clean_tests
          rsync -a --files-from=../visible_files.txt . ../clean_tests/
          cd ..
          rm visible_files.txt
          rm -rf temp_tests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: browserstack_tests
          path: clean_tests/
          retention-days: 5 